# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FoursquarePlaces' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for FoursquarePlaces
  pod 'Alamofire' 
  pod 'SDWebImageSwiftUI'
  pod 'Unrealm'
  pod 'ReachabilitySwift'
  
  target 'FoursquarePlacesTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'FoursquarePlacesUITests' do
    # Pods for testing
  end

end
